name: Подсчёт файлов
on: [push]
jobs:
  tests:
    name: Тесты скриптов
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Тест - существующая папка
    #   run: |
    #     chmod +x counter-test1.sh
    #     ./counter-test1.sh
    - name: Тест - недействительная папка
      run: |
        chmod +x counter-test2.sh
        ./counter-test2.sh
    - name: Тест - нет аргумента
      run: |
        chmod +x counter-test3.sh
        ./counter-test3.sh
        