name: Подсчёт файлов
on: [push]
jobs:
  tests:
    name: Тесты скриптов
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Тест
      run: |
        chmod +x counter-test.sh
        ./counter-test.sh